node-sshpk#81 add support for ed25519 private keys in pkcs8
TritonDataCenter/node-sshpk pull request #83
Opened 2022-05-26 00:36 UTC by arekinath

RFC8410 (PEM/X509 formats for Ed25519 and X25519) has been finalised for a while, this is the last piece of it that wasn't implemented in `sshpk` yet.

Bumps version to 1.18.0 since this adds an API feature (support for converting Ed25519 keys to pkcs8 format).

2022-05-26 14:52 UTC, danmcd commented
Please ACK that you've run "make test" including your new one.

2022-05-30 00:57 UTC, bahamat requested changes
Just one thing, then ready for merging.

2022-05-30 00:57 UTC, bahamat commented on lib/formats/pkcs8.js
> +	while (k.length > 32 && k[0] == 0x00)
jsl is complaining that this should be `===` not `==`. If that's fixed, `make check` will pass.

<https://jenkins.tritondatacenter.com/job/TritonDataCenter/job/node-sshpk/view/change-requests/job/PR-83/1/console>

2022-08-07 19:19 UTC, fernandoenzo commented
Excuse me, but is this project still alive? I saw that no commits have been made since January.
Why hasn't this feature been merged yet? Are there any plans to update this program?

Thanks

2022-08-07 19:36 UTC, bahamat commented
Yes it's still alive. It hasn't been committed because it doesn't pass style checks.

2022-09-13 12:04 UTC, gustavosbarreto commented
@arekinath Can you please fix the CI failure?

2023-10-19 17:24 UTC, bahamat commented
Merged in #92.

2023-10-19 17:24 UTC, closed without merging